---
- name: Gather running configuration from network devices
  hosts: CSR1kv
  gather_facts: no
  tasks:
    - name: Gather running configuration
      ios_config:
        authorize: yes
        config: show running-config
      register: output

    - name: Save output to file
      copy:
        content: "{{ output.stdout }}"
        dest: "./show_run_65070182_CSR1KV-Pod1-3.txt"  # Make sure this matches the filename in ansible_final.py